force-app/main/default/objects/Food_Option__c/Food_Option__c.object-meta.xml
<CustomObject>
    <label>Food Option</label>
    <nameField>
        <label>Food Options Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Food Options</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Food_Option__c/fields/Size__c.field-meta.xml
<CustomField>
    <fullName>Size__c</fullName>
    <label>Size</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Half</fullName>
            </value>
            <value>
                <fullName>Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/FoodOptionService.cls
/**
 * Invocable Apex class to query Food_Option__c records
 * Used by AgentForce agents to retrieve food options data
 */
public without sharing class FoodOptionService {
    
    /**
     * Invocable method to get all Food_Option__c records with specified fields
     * @return List of Food_Option__c records
     */
    @InvocableMethod(label='Get Food Options' description='Retrieves all Food Options with Name, Price and Size')
    public static List<Food_Option__c> getFoodOptions(LIST<String> foodPreferances) {
        return [
            SELECT Name, Price__c, Size__c 
            FROM Food_Option__c 
            
        ];
    }
}